name: AngularDartStacktraces
version: 0.0.1
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: "^5.0.0-alpha+11"
  angular_router: "^2.0.0-alpha+11"
  angular_forms: "^2.0.0-alpha+3"

dev_dependencies:
  build_runner: "^0.8.8"
  build_test: "^0.10.2+3"
  build_web_compilers: "^0.4.0+1"

